# Generated by Django 5.2.17 on 2026-09-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('profile', models.TextField(max_length=500)),
            ],
        ),
    ]
